# API Envoy IP: 172.10.0.10
# ref:
#   https://www.envoyproxy.io/docs/envoy/latest/configuration/configuration
#   https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/tls
#   https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket
#   https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter
static_resources:
  listeners:
  - name: listener_https
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443    
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            virtual_hosts:
            - name: api_servers
              domains: ["*"]
              routes:
              - match: {prefix: "/api"}
                route:
                  cluster: api_service
              - match: {prefix: "/"}
                route:
                  cluster: nginx_web_server
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: [ "h2,http/1.1" ]
            tls_certificates:
            - certificate_chain: {filename: "/etc/envoy/certs/atai-envoy.com.crt"}
              private_key: {filename: "/etc/envoy/certs/atai-envoy.com.key"}
            validation_context:
              trusted_ca:
                filename: "/etc/ssl/certs/ca-certificates.crt"

# ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-enum-config-cluster-v3-cluster-lbpolicy
  clusters:
  - name: nginx_web_server
    connect_timeout: 5s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: nginx_web_server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.10.0.111
                port_value: 443
        - endpoint:
            address:
              socket_address:
                address: 172.10.0.112
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

  - name: api_service
    connect_timeout: 2s
    type: STATIC
    lb_policy: RING_HASH
    http2_protocol_options: {}
    load_assignment:
      cluster_name: api_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.10.0.21
                port_value: 443
        - endpoint:
            address:
              socket_address:
                address: 172.10.0.22
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext


# ref: https://www.envoyproxy.io/docs/envoy/latest/operations/admin
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001